// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBliy62PGzQkwqwSbOeO5mReG6sE9owDE0',
    appId: '1:513031136510:web:cbc81acc56c731915831af',
    messagingSenderId: '513031136510',
    projectId: 'flutterauth-ab08d',
    authDomain: 'flutterauth-ab08d.firebaseapp.com',
    storageBucket: 'flutterauth-ab08d.firebasestorage.app',
    measurementId: 'G-ZC56Y41ZGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhz0mYR2OcLKwh2q7ajlnPFsTj8diqIQs',
    appId: '1:513031136510:android:9f5316e81ba45a225831af',
    messagingSenderId: '513031136510',
    projectId: 'flutterauth-ab08d',
    storageBucket: 'flutterauth-ab08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2BVZ0jGdgGWstxF0-4HFYBOZHs9n_nI',
    appId: '1:513031136510:ios:d2f6c339402ee5255831af',
    messagingSenderId: '513031136510',
    projectId: 'flutterauth-ab08d',
    storageBucket: 'flutterauth-ab08d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2BVZ0jGdgGWstxF0-4HFYBOZHs9n_nI',
    appId: '1:513031136510:ios:d2f6c339402ee5255831af',
    messagingSenderId: '513031136510',
    projectId: 'flutterauth-ab08d',
    storageBucket: 'flutterauth-ab08d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBliy62PGzQkwqwSbOeO5mReG6sE9owDE0',
    appId: '1:513031136510:web:833f3c9add6c25be5831af',
    messagingSenderId: '513031136510',
    projectId: 'flutterauth-ab08d',
    authDomain: 'flutterauth-ab08d.firebaseapp.com',
    storageBucket: 'flutterauth-ab08d.firebasestorage.app',
    measurementId: 'G-JQ11CMW5Z8',
  );
}
